/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import { initializeApp, getApps, getApp, FirebaseApp } from "firebase/app";
import { getAuth, Auth } from "firebase/auth";
import { getFirestore, Firestore } from "firebase/firestore";

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID
};

console.log("🔍 [Firebase] Configuration loaded:", {
  ...firebaseConfig,
  apiKey: firebaseConfig.apiKey ? (firebaseConfig.apiKey.substring(0, 6) + "...") : "MISSING"
});

// Check if Firebase is properly configured with real values
export const isFirebaseConfigured = !!(
  firebaseConfig.apiKey && 
  firebaseConfig.apiKey !== 'AIzaSy_REPLACE_ME' &&
  !firebaseConfig.apiKey.includes('DummyKey')
);

/**
 * PRODUCTION-LEVEL FIREBASE SINGLETON
 * This pattern ensures that Firebase is initialized exactly once and
 * services are exported as ready-to-use instances.
 */
const app: FirebaseApp | undefined = isFirebaseConfigured 
  ? (getApps().length > 0 ? getApp() : initializeApp(firebaseConfig))
  : undefined;

const auth: Auth | undefined = app ? getAuth(app) : undefined;
const db: Firestore | undefined = app ? getFirestore(app) : undefined;

// Robust Diagnostic Logging
if (typeof window !== "undefined") {
    console.log("🔥 Firebase initialized. DB instance:", db);
    if (isFirebaseConfigured && !db) {
        console.error("❌ [Firebase] Critical: db is undefined despite valid configuration.");
    }
}

// Named exports as requested
export { app, auth, db };

/**
 * Connectivity helper for Safe Mode flows.
 */
export const isDbReady = (): boolean => {
  return !!(isFirebaseConfigured && db);
};

/**
 * Sanitizes an object before sending it to Firestore.
 * - Removes the "id" field (Firestore generates its own IDs).
 * - Recursively removes undefined values.
 */
export const sanitizeData = (data: any): any => {
    if (data === null || data === undefined) return data;
    
    // Handle Arrays
    if (Array.isArray(data)) {
        return data.map(item => sanitizeData(item));
    }

    // Handle Objects (only plain objects)
    if (typeof data === 'object' && data.constructor.name === 'Object') {
        const cleanData = { ...data };
        // Remove 'id' field as it's typically auto-generated by Firestore
        if ('id' in cleanData) {
            delete cleanData.id;
        }

        // Recursively remove undefined values
        Object.keys(cleanData).forEach(key => {
            if (cleanData[key] === undefined) {
                delete cleanData[key];
            } else {
                cleanData[key] = sanitizeData(cleanData[key]);
            }
        });
        return cleanData;
    }

    return data;
};

// maintain backward compatibility for shared lib reference if any
export const firebaseApp = app;
